package com.company;

public enum Subjects {
    GEOMETRY_AND_ALGEBRA,
    MATHEMATICAL_ANALYSIS,
    PROGRAMMING,
    FOREIGN_LANGUAGE,
    BELARUSIAN_LANGUAGE,
    PHYSICAL_CULTURE,
    HISTORY,
    EDUCATIONAL_PRACTICE,
    DISCRETE_MATHEMATICS_AND_MATHEMATICAL_LOGIC,
    COMPUTATIONAL_ALGEBRA_METHODS,
    INTRODUCTION_TO_COMPUTER_AND_DATA_MINING,
    DIFFERENTIAL_EQUATIONS,
    ECONOMICS,
}